### ISSUE TITLE
Include pageX/Y in the TouchInit dictionary

### ISSUE THREAD

**Issue by AFBarstow** [w3c/touch-events#33] opened 2015-10-22 15:41 UTC
Why are the pageX and pageY attributes not explicitly included in the [TouchInit dictionary](https://w3c.github.io/touch-events/#touch-interface)?

**Comment by mbrubeck** [comment] 2015-10-22 16:08
Duplicate of #28.

**Closed as completed by mbrubeck** 2015-10-22 16:08 UTC

**Comment by AFBarstow** [comment] 2015-10-22 20:14
Thanks Matt! 
(If someone else asks about this, we should consider adding a non-normative note that explains the absence of these two attributes from the dictionary.)
